#!/bin/bash
set -eu
set -o pipefail

AWS=${AWS_COMMAND:-aws}

$AWS autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$1" \
  | jq -r '.AutoScalingGroups | .[] | .Instances | .[] | .InstanceId'
