#!/usr/bin/env bash
set -u
set -o errexit
set -o pipefail

function command_help {
  echo "\
    $(basename "$0") CLUSTER SERVICE
  "
}

function error_msg() {
  {
  echo ""
  echo "ERROR: $*"
  echo ""
  } >&2
}

function exit_msg() {
  error_msg "$@"
  command_help >&2
  exit 1
}


if [[ -z ${1+undefined-guard} ]]; then
  exit_msg "expected a cluster"
fi
cluster="$1"
shift

if [[ -z ${1+undefined-guard} ]]; then
  exit_msg "expected a service"
fi
service="$1"
shift

AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
export AWS_ARGS="${AWS_ARGS:-"--output json --region $AWS_DEFAULT_REGION"}"
function AWS_COMMAND() { aws "$@" $AWS_ARGS ; }

result=$(AWS_COMMAND ecs describe-services --cluster "$cluster" --service "$service")
if [[ -z "$result" ]] || [[ ! -z "$(echo "$result" | jq '.failures[]')" ]] ; then
  exit_msg "deployment not found"
fi
echo "$result" | jq '.services[0].deployments[] | select(.status == "PRIMARY")'
