#!/bin/bash
set -eu
set -o pipefail

AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
export AWS_ARGS="${AWS_ARGS:-"--output json --region $AWS_DEFAULT_REGION"}"
function AWS_COMMAND() { aws "$@" $AWS_ARGS ; }

AWS_COMMAND ec2 describe-instances --instance-ids "$@" \
    | jq -r '.Reservations | .[] | .Instances | .[] | .PrivateIpAddress'
